# Configuration Unique pour SonarQube
sonar.projectKey=fullstakers-monorepo
sonar.projectName=Fullstakers Project
sonar.projectVersion=1.0.0

# On définit les sources
sonar.sources=back-end/src, front-end/src
sonar.sourceEncoding=UTF-8

# Exclusions pour passer au VERT (Passed)
# On exclut la couverture pour que le score de 0% ne bloque pas le projet
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*

# Exclusions standards
sonar.exclusions=node_modules/**, **/dist/**, **/build/**, voice-api/**, ml-service/**, venv/**, **/*.spec.ts, **/*.test.js
