server {
    listen 80;
    
    # Configuration principale pour résoudre le problème React Router
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Si le fichier/dossier n'existe pas, Nginx renvoie index.html (pour que React gère la route)
        try_files $uri $uri/ /index.html; 
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
